baseURL: https://christopherisene.se/
languageCode: en-us
title: Christopher Isene

enableGitInfo: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false
pygmentsUseClasses: false
mainsections: ["home", "contact"]

disableKinds: ["taxonomy","taxonomyTerm","RSS"]

defaultContentLanguage: en

minify:
  disableXML: true
  minifyOutput: false

languages:
  en:
    languageName: "English"
    weight: 1
    #taxonomies:
    #  category: categories
    #  tag: tags
    #  series: series
    menu:
      main:
      - name: home
        title: Home
        url: /
        weight: 1

      - name: contact
        title: Contact
        url: /contact
        weight: 2

      - name: current-and-past
        title: Current and Past
        url: /current-and-past
        weight: 3

      - name: projects
        title: Projects
        url: /projects
        weight: 4

      - name: skills
        title: Skills
        url: /skills
        weight: 5

      - name: travels
        title: Travels
        url: /travels
        weight: 6

outputs:
  home:
  - HTML


params:
  env: production
  description: My home at the Internet
  author: Christopher Isene

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: false
  ShowPageNums: false
  showPowerBy: false
  ShowToc: false
  comments: false
  uglyURLs: false

  google-site-verification: "j1BZfIlWMVNs--J79vYca4zfq-4pL3leEPe8FvHj9b4"
  MobileOptimized: width
  HandheldFriendly: true

  opengraph:
    type: website
    title: Christopher Isene
    description: Here, now and present
    url: https://christopherisene.se/
    site_name: Christopher Isene
    locale: en_US
    image:
      content: images/christopher-isene-20140906.jpg
      width: 960
      height: 960
      alt: Silly Selfie

  profileMode:
    enabled: false
    title: Silly Selfie
    imageUrl: image/christopher-isene-20140906.jpg
    imageTitle: "Silly selfie"
    imageWidth: 960
    imageHeight: 960
    buttons:
      #- name: Archives
      #  url: archives
      #- name: Tags
      #  url: tags



markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

modules:
  mounts:
  - source: static
  - target: static
