baseURL: https://christopherisene.se/
languageCode: en-us
title: Christopher Isene

enableGitInfo: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["home", "contact"]

defaultContentLanguage: en

minify:
  disableXML: false
  minifyOutput: false

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
      - name: home
        title: Home
        url: /
        weight: 1

      - name: contact
        title: Contact
        url: /contact/
        weight: 2

      - name: current-and-past
        title: Current and Past
        url: /current-and-past/
        weight: 3

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  env: production
  description: My home at the Internet
  author: Christopher Isene

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: false

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

modules:
  mounts:
  - source: static
  - target: static
